name             'upstart'
maintainer       'Tim Johnson'
maintainer_email 'tjj9020@gmail.com'
license          'All rights reserved'
description      'Installs/Configures upstart'
long_description 'Installs/Configures upstart'
version          '0.1.40'

depends 'rvm'
depends 'gbg_familyfinder'
depends 'python'
depends 'gbg_yum_repo'
depends 'yum-epel'
depends 'sudo'
depends 'gbg_sudo'
depends 'ssh'

